version: '3'
services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf:/etc/letsencrypt/
    networks:
      - global

  fastapi:
    container_name: fastapi
    restart: unless-stopped
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./fastapi:/app
    networks:
      - global

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot/ --email uvuv.space@gmail.com -d api.uvuv643.ru -d uvuv643.ru --agree-tos --cert-name tourism

  react:
    container_name: react
    restart: unless-stopped
    build:
      context: ./react
      dockerfile: Dockerfile
    networks:
      - global

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/usr/local/redis/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ./redis/.env
    networks:
      - global
    command:
      redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}

networks:
  global:
    driver: bridge

volumes:
  redis-volume:
    driver: local